server:
  port: 8189
  servlet:
    context-path: /hw7
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:/localhost:5489/hw7
      user: postgres
      password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
